[2022-10-30 07:44:57,994] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: etl_denue.get_files scheduled__2022-09-01T00:00:00+00:00 [queued]>
[2022-10-30 07:44:57,999] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: etl_denue.get_files scheduled__2022-09-01T00:00:00+00:00 [queued]>
[2022-10-30 07:44:57,999] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-10-30 07:44:57,999] {taskinstance.py:1377} INFO - Starting attempt 21 of 25
[2022-10-30 07:44:57,999] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-10-30 07:44:58,006] {taskinstance.py:1397} INFO - Executing <Task(SeleniumOperator): get_files> on 2022-09-01 00:00:00+00:00
[2022-10-30 07:44:58,012] {standard_task_runner.py:52} INFO - Started process 9155 to run task
[2022-10-30 07:44:58,014] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'etl_denue', 'get_files', 'scheduled__2022-09-01T00:00:00+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/get_raw_files/scrapper.py', '--cfg-path', '/tmp/tmpgqwg3o3n', '--error-file', '/tmp/tmpotlbwpvs']
[2022-10-30 07:44:58,015] {standard_task_runner.py:80} INFO - Job 23: Subtask get_files
[2022-10-30 07:44:58,047] {task_command.py:371} INFO - Running <TaskInstance: etl_denue.get_files scheduled__2022-09-01T00:00:00+00:00 [running]> on host 1dd15365b03f
[2022-10-30 07:44:58,118] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Freakisimo
AIRFLOW_CTX_DAG_ID=etl_denue
AIRFLOW_CTX_TASK_ID=get_files
AIRFLOW_CTX_EXECUTION_DATE=2022-09-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=21
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-01T00:00:00+00:00
[2022-10-30 07:44:58,215] {selenium_hook.py:14} INFO - initialised hook
[2022-10-30 07:44:58,215] {selenium_hook.py:18} INFO - getting ip
[2022-10-30 07:44:58,215] {selenium_hook.py:31} INFO - creating driver
[2022-10-30 07:44:58,304] {selenium_hook.py:46} INFO - remote ready
[2022-10-30 07:45:31,299] {logging_mixin.py:115} INFO - Message:
[2022-10-30 07:45:31,369] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/plugins/operators/selenium_operator.py", line 24, in execute
    hook.run_script(self.script, self.script_args)
  File "/opt/airflow/plugins/hooks/selenium_hook.py", line 56, in run_script
    script(self.driver, *args)
  File "/opt/airflow/dags/utils/get_files.py", line 36, in selenium_scrapper
UnboundLocalError: local variable 'innerHTML' referenced before assignment
[2022-10-30 07:45:31,375] {taskinstance.py:1420} INFO - Marking task as UP_FOR_RETRY. dag_id=etl_denue, task_id=get_files, execution_date=20220901T000000, start_date=20221030T074457, end_date=20221030T074531
[2022-10-30 07:45:31,382] {standard_task_runner.py:97} ERROR - Failed to execute job 23 for task get_files (local variable 'innerHTML' referenced before assignment; 9155)
[2022-10-30 07:45:31,412] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-10-30 07:45:31,436] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
